# Generated by Django 3.1.5 on 2021-01-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('following', models.ManyToManyField(related_name='follower', to='user.User')),
                ('liked_posts', models.ManyToManyField(related_name='liked_users', to='post.Post')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
