# Generated by Django 3.2 on 2021-05-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
