# Generated by Django 3.1.5 on 2021-03-14 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20210123_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.comment'),
        ),
    ]
